version: "3.3"
# Указываем раздел со связанными сервисами
services:
  # Первый сервис, nginx
  nginx:
    image: nginx:latest
    restart: always
    # Пробрасываем порты 80 для http и 443 для https
    ports:
      - "80:80"
      - "443:443"
    # Опциональный параметр с именем контейнера
    container_name: proxy_nginx
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
  # Второй сервис Nuxt.js приложение
  crm:
    # Используем ранее собранный образ
    image: volkovoleg/goodwillcrm
    container_name: crm
    restart: always
    environment:
      API_URL: https://api.goodfil.com
    # Так же пробрасываем порт на котором висит приложение
    ports:
      - "3331:3331"
  catalog:
    # Используем ранее собранный образ
    image: volkovoleg/goodwillcatalog
    container_name: catalog
    restart: always
    # Так же пробрасываем порт на котором висит приложение
    ports:
      - "3333:3333"


